name: Compilar, Testear, Analizar y Publicar NuGet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Compilar & Publicar Paquetes NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # =============================
      # RESTAURAR DEPENDENCIAS
      # =============================
      - name: Restaurar dependencias
        run: |
          dotnet restore ATM/ATM.Domain/ATM.Domain.csproj
          dotnet restore Payment/Payment.Domain/Payment.Domain.csproj

      # =============================
      # PRUEBAS
      # =============================
      - name: Ejecutar pruebas de ATM
        run: dotnet test ATM/ATM.Domain/ATM.Domain.csproj --logger trx --no-build

      - name: Ejecutar pruebas de Payment
        run: dotnet test Payment/Payment.Domain/Payment.Domain.csproj --logger trx --no-build

      # =============================
      # INSTALAR SONARSCANNER
      # =============================
      - name: Instalar SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      # =============================
      # ANÁLISIS SONARCLOUD
      # =============================
      - name: Iniciar análisis SonarCloud
        run: |
          dotnet sonarscanner begin /k:"erickorganizacion_lab4" /o:"erickorganizacion" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        
      # =============================
      # CONSTRUCCIÓN DE PAQUETES NUGET
      # =============================
      - name: Crear paquetes NuGet
        run: |
          dotnet pack ATM/ATM.Domain/ATM.Domain.csproj --configuration Release --output ./nupkgs
          dotnet pack Payment/Payment.Domain/Payment.Domain.csproj --configuration Release --output ./nupkgs

      # =============================
      # PUBLICAR PAQUETES NUGET
      # =============================
      - name: Publicar paquetes en NuGet
        run: |
          for file in ./nupkgs/*.nupkg
          do
            dotnet nuget push "$file" \
              --source https://api.nuget.org/v3/index.json \
              --api-key ${{ secrets.NUGET_API_KEY }} \
              --skip-duplicate
          done

      # =============================
      # FINALIZAR ANÁLISIS SONARCLOUD
      # =============================
      - name: Finalizar análisis SonarCloud
        run: |
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
