name: Compilar y Analizar con SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Necesario para SonarCloud

    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Ejecutar pruebas con cobertura
      run: dotnet test --no-build --collect:"XPlat Code Coverage"

    - name: Análisis SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para integración con PRs
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: .
        args: >
          /d:sonar.organization=erickorganizacion
          /d:sonar.projectKey=erickorganizacion_lab4
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
          /d:sonar.coverage.exclusions="**Test*.cs"
          /d:sonar.cpd.exclusions="**Test*.cs"
          /d:sonar.dotnet.excludeTestProjects=true

    - name: Compilar el proyecto
      run: dotnet build --configuration Release --no-restore

    - name: Publicar NuGet
      run: |
        dotnet pack --configuration Release --output ./nupkgs --no-build
