name: Publish Documentation

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Instalar DocFX con .NET tool
        run: |
          dotnet tool install -g docfx
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Generar documentación ATM
        working-directory: ATM
        run: |
          docfx metadata docfx.json
          docfx build docfx.json

      - name: Generar documentación Payment
        working-directory: Payment
        run: |
          docfx metadata docfx.json
          docfx build docfx.json

      - name: Preparar carpeta para GitHub Pages
        run: |
          mkdir -p deploy
          cp -r ATM/_site deploy/atm
          cp -r Payment/_site deploy/payment

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
